FROM docker.io/python:3.10@sha256:c0352a2c64efe4cc08b198e90b97ed7e08897518c4bee99647e3eaf676e84951 as algorand-contracts-build

RUN python3 -m pip install virtualenv
COPY Pipfile.lock Pipfile.lock
COPY Pipfile Pipfile

RUN python3 -m pip install pipenv
RUN pipenv install
RUN mkdir teal
COPY *.py .

RUN pipenv run python3 admin.py --mainnet --genTeal 

FROM scratch AS algorand-contracts-export
COPY --from=algorand-contracts-build /teal/* .


