FROM docker.io/python:3.10@sha256:d719cce3399b609511e3a8f0e7171bb45a63cce24c14084ea33d705e162745fd as algorand-contracts-build

RUN python3 -m pip install virtualenv
COPY Pipfile.lock Pipfile.lock
COPY Pipfile Pipfile

RUN python3 -m pip install pipenv
RUN pipenv install
RUN mkdir teal
COPY *.py .

RUN pipenv run python3 admin.py --mainnet --genTeal 

FROM scratch AS algorand-contracts-export
COPY --from=algorand-contracts-build /teal/* .


